#+TITLE: esphome-pulse
#+AUTHOR: Paul Schulz
#+OPTIONS: toc:nil num:nil

* Overview

This is an [[https://esphome.io][ESPHome]] project called *esphome-=pulse*=, based on the **Home Assistant Glow**
which was originally created in 2011. 

For more background on this project see: https://glow-energy.io

* Repository

- GitHub: https://github.com/PaulSchulz/esphome-pulse
- Clone: ~git clone git@github.com:PaulSchulz/esphome-pulse.git~

* Software
** Common YAML files
The firmware makes use of a master file, with a collection of shared YAML files
in 'common/'.

** Using the secrets.html
A dummy 'secrets' file has been included in the repository. Edit it to match
your Wifi and Hom Assistant API credentials.

Please do not include this file in any pull requests.

To ensure this, I include the foillowing alias in my .git/config file

#+begin_example
[alias]
    ignore = update-index --assume-unchanged
    unignore = update-index --no-assume-unchanged
    ignored = !git ls-files -v | grep "^[[:lower:]]"
#+end_example

and then set changes to this file to be ignored by git in future commits.

#+begin_src sh
DIR$ git ignore esphome/secrets.yaml
DIR$ git ignored
h esphome/secrets.yaml
#+end_src

Multiple alternative local secrets files in 'esphome/' can created using filenames of the form
'secrets-ID.yaml'. This are set to be ignored in '.gitignore'.

* License

This project is licensed under the MIT License. See the [[file:LICENSE][LICENSE]] file for details.

* Resources
 TBD
